name: publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2

    - name: Checkout master
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - id: get_version
      uses: battila7/get-version-action@v2

    - name: Build binary
      run: make bin

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload release binaries
      uses: alexellis/upload-assets@0.2.2
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        asset_paths: '["./build/hotweb*"]'

    - name: Update README on master branch with new version
      env:
        VERSION: ${{ steps.get_version.outputs.version-without-v }}
      run: |
       git config --global user.email "action@github.com"
       git config --global user.name "Github Action"
       git checkout master
       sed -i "s/v[0-9]\.[0-9]\.[0-9]\+/v${VERSION}/" README.md
       git commit -am "Update README with ${VERSION}"
       git push origin master
