name: update-version-refs

on:
  release:
    types:
    - created
    - released

jobs:
  update-version-refs:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout master
      uses: actions/checkout@v2
      with:
        ref: master

    - id: latest
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        repository: ${{ github.repository }}

    - name: Update master branch with new version ref
      run: |
       git config --global user.email "action@github.com"
       git config --global user.name "Github Action"
       make update-ver-ref LATEST=${{ steps.latest.outputs.release }}
       git commit -am "Update references with ${{ steps.latest.outputs.release }}"
       git push origin master
